from .user import * # noqa
from .speaker import * # noqa
from .certificate import * # noqa
from .course import * # noqa
from .course_files import * # noqa
from .drug import * # noqa
from .pharmacist_company import * # noqa
from .timecodes import * # noqa
from .user_module_completion_requirements import * # noqa
from .module import * # noqa
from .tags import * # noqa