# Generated by Django 4.2.6 on 2023-12-20 15:03

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_tag_delete_versionhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='course/cover_image/%Y/%m/%d', verbose_name='Image')),
                ('disclaimer', models.TextField(verbose_name='Disclaimer')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='education_files', verbose_name='File')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Course File',
                'verbose_name_plural': 'Course Files',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'db_table': 'drug',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('video', models.FileField(upload_to='module/video', verbose_name='Video')),
                ('cover_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='module/cover_image/%Y/%m/%d', verbose_name='Cover Image')),
                ('disclaimer', models.TextField(verbose_name='Disclaimer')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='module.course')),
                ('drugs', models.ManyToManyField(to='module.drug', verbose_name='Drugs')),
                ('module_files', models.ManyToManyField(to='module.coursefiles', verbose_name='Module Files')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PharmacistCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Pharmacist Company',
                'verbose_name_plural': 'Pharmacist Companies',
                'db_table': 'pharmacist_company',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('family_name', models.CharField(max_length=255, verbose_name='Family name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('avatar', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='speaker/avatar/', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'speaker',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('start_time', models.DurationField(verbose_name='Start Time')),
                ('end_time', models.DurationField(verbose_name='End Time')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'TimeCode',
                'verbose_name_plural': 'TimeCodes',
                'db_table': 'time_code',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='module',
            name='pharmacist_company',
            field=models.ManyToManyField(to='module.pharmacistcompany', verbose_name='Pharmacist Company'),
        ),
        migrations.AddField(
            model_name='module',
            name='speaker',
            field=models.ManyToManyField(to='module.speaker', verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=models.ManyToManyField(to='common.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='drugs',
            field=models.ManyToManyField(to='module.drug', verbose_name='Drugs'),
        ),
        migrations.AddField(
            model_name='course',
            name='pharmacist_company',
            field=models.ManyToManyField(to='module.pharmacistcompany', verbose_name='Pharmacist Company'),
        ),
        migrations.AddField(
            model_name='course',
            name='speaker',
            field=models.ManyToManyField(to='module.speaker', verbose_name='Speaker'),
        ),
    ]
