# Generated by Django 4.2.6 on 2023-12-21 07:41

import apps.module.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='course.py/cover_image/%Y/%m/%d', verbose_name='Image')),
                ('disclaimer', models.TextField(verbose_name='Disclaimer')),
                ('certificate_html_template', models.FileField(help_text='Use {{ full_name }} to show user full name.\n            Use {{ course_title }} to show course.py title.\n            Use {{ qrcode_url }} to show QR code url.\n            Use {{ absolute_path }} to show absolute path.', null=True, upload_to='course_certificate_html_templates', verbose_name='Certificate HTML Template')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='education_files', verbose_name='File')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Course File',
                'verbose_name_plural': 'Course Files',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'db_table': 'drug',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('video', models.FileField(upload_to='module/video', verbose_name='Video')),
                ('cover_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='module/cover_image/%Y/%m/%d', verbose_name='Cover Image')),
                ('disclaimer', models.TextField(verbose_name='Disclaimer')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='module.course')),
                ('drugs', models.ManyToManyField(blank=True, to='module.drug', verbose_name='Drugs')),
                ('module_files', models.ManyToManyField(blank=True, to='module.coursefiles', verbose_name='Module Files')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PharmacistCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Pharmacist Company',
                'verbose_name_plural': 'Pharmacist Companies',
                'db_table': 'pharmacist_company',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('family_name', models.CharField(max_length=255, verbose_name='Family name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('avatar', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='speaker/avatar/', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'speaker',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('start_time', models.DurationField(verbose_name='Start Time')),
                ('end_time', models.DurationField(verbose_name='End Time')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecodes', to='module.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'TimeCode',
                'verbose_name_plural': 'TimeCodes',
                'db_table': 'time_code',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='module',
            name='pharmacist_company',
            field=models.ManyToManyField(blank=True, to='module.pharmacistcompany', verbose_name='Pharmacist Company'),
        ),
        migrations.AddField(
            model_name='module',
            name='speaker',
            field=models.ManyToManyField(blank=True, to='module.speaker', verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_files',
            field=models.ManyToManyField(blank=True, to='module.coursefiles', verbose_name='Course Files'),
        ),
        migrations.AddField(
            model_name='course',
            name='drugs',
            field=models.ManyToManyField(blank=True, to='module.drug', verbose_name='Drugs'),
        ),
        migrations.AddField(
            model_name='course',
            name='pharmacist_company',
            field=models.ManyToManyField(blank=True, to='module.pharmacistcompany', verbose_name='Pharmacist Company'),
        ),
        migrations.AddField(
            model_name='course',
            name='speaker',
            field=models.ManyToManyField(blank=True, to='module.speaker', verbose_name='Speaker'),
        ),
        migrations.CreateModel(
            name='UserModuleCompletionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_video_played', models.BooleanField(default=False, verbose_name='Is Video Played')),
                ('is_files_downloaded', models.BooleanField(default=False, verbose_name='Is Files Downloaded')),
                ('is_test_passed', models.BooleanField(default=False, verbose_name='Is Tests Passed')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module', verbose_name='Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserModuleCompletionRequirement',
                'verbose_name_plural': 'UserModuleCompletionRequirements',
                'db_table': 'user_module_completion_requirements',
                'ordering': ('-id',),
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cid', models.CharField(default=apps.module.utils.randomize_certificate_number, max_length=255, verbose_name='CID')),
                ('file', models.FileField(null=True, upload_to='certificates', verbose_name='File')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='module.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
